import os, sys , math, re, requests, json, time, random
from bs4 import BeautifulSoup as soup
import pandas as pd
from fake_useragent import UserAgent



Countries_en = {'Global': 'GLOBAL',
 'Germany': 'DE',
 'Saudi Arabia': 'SA',
 'Argentina': 'AR',
 'Australia': 'AU',
 'Austria': 'AT',
 'Bangladesh': 'BD',
 'Belgium': 'BE',
 'Belarus': 'BY',
 'Brazil': 'BR',
 'Bulgaria': 'BG',
 'Canada': 'CA',
 'Czech Republic': 'CZ',
 'Chile': 'CL',
 'Colombia': 'CO',
 'South Korea': 'KR',
 'Costa Rica': 'CR',
 'Croatia': 'HR',
 'Denmark': 'DK',
 'Egypt': 'EG',
 'United Arab Emirates': 'AE',
 'Slovakia': 'SK',
 'Slovenia': 'YES',
 'Spain': 'ES',
 'United States': 'US',
 'Estonia': 'EE',
 'Philippines': 'PH',
 'Finland': 'FI',
 'France': 'FR',
 'Ghana': 'GH',
 'Greece': 'GR',
 'Hong Kong': 'HK',
 'Hungary': 'HU',
 'India': 'IN',
 'Indonesia': 'ID',
 'Ireland': 'IE',
 'Israel': 'IL',
 'Italy': 'IT',
 'Japan': 'JP',
 'Kazakhstan': 'KZ',
 'Kenya': 'KE',
 'Latvia': 'LV',
 'Lithuania': 'LT',
 'Malaysia': 'MY',
 'Mexico': 'MX',
 'Nigeria': 'NG',
 'Norway': 'NO',
 'New Zealand': 'NZ',
 'Netherlands': 'NL',
 'Pakistan': 'PK',
 'Panama': 'PA',
 'Peru': 'PE',
 'Poland': 'PL',
 'Portugal': 'PT',
 'Puerto Rico': 'PR',
 'United Kingdom': 'GB',
 'Romania': 'RO',
 'Russia': 'RU',
 'Serbia': 'RS',
 'Singapore': 'SG',
 'South Africa': 'ZA',
 'Sweden': 'SE',
 'Switzerland': 'CH',
 'Thailand': 'TH',
 'Taiwan': 'TW',
 'Turkey': 'TR',
 'Ukraine': 'UA',
 'Uruguay': 'UY',
 'Vietnam': 'VN',
 'Zimbabwe': 'ZW'}